name: chore_master
services:
  mongodb_replica_set:
    container_name: mongodb_replica_set
    command: mongod --port 27019 --replSet rs0
    healthcheck:
      test: |
        mongosh --port 27019 --eval "try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27019' }] }).ok }"
      start_period: 0s
      interval: 500ms
      timeout: 5s
      retries: 5
    image: mongo:7
    ports:
      - 27019:27019
    volumes:
      - ./mongodb_replica_set/volume_data:/data/db